using PlainElastic.Net.Utils;

namespace PlainElastic.Net.Queries
{
    /// <summary>
	/// A single-value metrics aggregation that computes the average of numeric values that are extracted from the aggregated documents.
	/// These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.
	/// see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html
    /// </summary>
    public class AvgAggregation<T> : ValueAggregationBase<AvgAggregation<T>, T>
    {

        protected override string ApplyAggregationBodyJsonTemplate(string body)
        {
            return "'avg': {{ {0} }}".AltQuoteF(body);
        }
        
    }
}