using PlainElastic.Net.Utils;

namespace PlainElastic.Net.Queries
{
    /// <summary>
	/// A single-value metrics aggregation that counts the number of values that are extracted from the aggregated documents.
	/// These values can be extracted either from specific fields in the documents, or be generated by a provided script.
	/// Typically, this aggregator will be used in conjunction with other single-value aggregations.
	/// For example, when computing the avg one might be interested in the number of values the average is computed over.
	/// see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-valuecount-aggregation.html
    /// </summary>
	public class ValueCountAggregation<T> : ValueAggregationBase<ValueCountAggregation<T>, T>
    {

        protected override string ApplyAggregationBodyJsonTemplate(string body)
        {
            return "'value_count': {{ {0} }}".AltQuoteF(body);
        }
        
    }
}