using PlainElastic.Net.Utils;

namespace PlainElastic.Net.Queries
{
    /// <summary>
	/// A single-value metrics aggregation that keeps track and returns the minimum value among numeric values extracted from the aggregated documents.
	/// These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.
	/// see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-min-aggregation.html
    /// </summary>
    public class MinAggregation<T> : ValueAggregationBase<MinAggregation<T>, T>
    {
  
        protected override string ApplyAggregationBodyJsonTemplate(string body)
        {
            return "'min': {{ {0} }}".AltQuoteF(body);
        }
        
    }
}