using PlainElastic.Net.Utils;

namespace PlainElastic.Net.Queries
{
    /// <summary>
    /// A multi-value metrics aggregation that computes stats over numeric values extracted from the aggregated documents. 
    /// These values can be extracted either from specific numeric fields in the documents, or be generated by a provided script.
	/// The stats that are returned consist of: min, max, sum, count and avg.
	/// see http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-aggregations-metrics-stats-aggregation.html
    /// </summary>
    public class StatsAggregation<T> : ValueAggregationBase<StatsAggregation<T>, T>
    {
        protected override string ApplyAggregationBodyJsonTemplate(string body)
        {
            return "'stats': {{ {0} }}".AltQuoteF(body);
        }
        
    }
}